services:
  yishankeji:
    build:
      context: .
      dockerfile: Dockerfile
    image: crpi-jo8sc8us8vqvvoq7.cn-hangzhou.personal.cr.aliyuncs.com/get1/111:latest
    container_name: yishankeji
    restart: always
    ports:
      - "8017:8017"
    volumes:
      - ./data:/app/data
    environment:
      - HOST=0.0.0.0
      - PORT=8017
      - ACCESS_PASSWORD=${ACCESS_PASSWORD:-123456lfs}
